FROM wordpress:latest

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Podstawowa konfiguracja w pliku, resztę przekażemy przez Docker Compose
RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/tmp/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini